Connecting sports account
Revenite/amputee-rehab-app-monorepo pull request #105
Opened 2020-09-04 09:22 UTC by bolubajo7

# Description

Created the other fitness account screen that enables users to suggest other fitness accounts they would like to connect to the Revenite app

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2020-09-04 19:31 UTC, hb308 commented
Good work so far Bolu! I think it might be worth using some of the styled components which have been created or you can create some if you feel like it is needed.

2020-09-07 10:04 UTC, ndeasy reviewed
Can you ignore .DS_Store files

2020-09-07 10:04 UTC, ndeasy commented on mobile/android/.gradle/buildOutputCleanup/cache.properties
>  gradle.version=6.1.1
Resolve this conflict

2020-09-07 10:05 UTC, ndeasy commented on mobile/src/navigation/MainStackNavigation/MainStackNavigation.js
> +
Extra spacing not really needed

2020-09-07 10:06 UTC, ndeasy commented on mobile/src/screens/SportsAccountScreen/SportsAccountScreen.jsx
> +        const url = 'mailto:reveniteteam@example.com?subject=Add new sports account';
Do we have an actual email or is that a separate ticket? Maybe add a TODO here

2020-09-07 10:16 UTC, ndeasy commented on mobile/src/screens/SportsAccountScreen/SportsAccountScreen.jsx
> +    }
Isn't the button already a styled component? Do we need these styles or is this button custom

2020-09-07 10:17 UTC, ndeasy requested changes
Resolve the git conflict and add .DS_Store to your ignore file

2020-09-07 11:54 UTC, jchiversAND commented on mobile/src/screens/SportsAccountScreen/SportsAccountScreen.jsx
> +                <Row/>
The Row component is designed for aligning other components together in a row, such as two Buttons that want to be sat in a Row, rather than for spacing.

I'd suggest having something like a margin-bottom to whatever component sits above to create the space between the two :)

2020-09-07 12:00 UTC, jchiversAND requested changes

2020-09-07 12:00 UTC, jchiversAND commented on mobile/src/screens/SportsAccountScreen/SportsAccountScreen.jsx
> +const styles = StyleSheet.create({
Emotion (Styled Components) should be used for any custom styling needed to keep it consistent with what's been used already, rather than stylesheets on inline styling :) 

https://emotion.sh/docs/@emotion/native

2020-09-07 13:25 UTC, bolubajo7 commented on mobile/src/screens/SportsAccountScreen/SportsAccountScreen.jsx
> +        const url = 'mailto:reveniteteam@example.com?subject=Add new sports account';
We don't have an actual email. The current email is just a placeholder. I will added a TODO there

2020-09-07 16:22 UTC, bolubajo7 commented on mobile/src/screens/SportsAccountScreen/SportsAccountScreen.jsx
> +    }
It is a customised button with an icon in it on the left. I have created a custom button component for this.

2020-09-08 12:00 UTC, jchiversAND commented on mobile/src/screens/SportsAccountScreen/SportsAccountScreen.jsx
> +    const Description = styled.Text ({
The Text component can take in a margin as a prop, so instead of needing to use Emotion here, you could have on line 39:

<Text margin={'0, 0, 40'}>....</Text>

2020-09-08 12:07 UTC, jchiversAND commented on mobile/src/styles/components/CustomButton.js
> +import React from 'react';
Is there something specific about this CustomButton that we can't just use the Button component for instead?

Not sure if this component is needed.

2020-09-08 12:32 UTC, bolubajo7 commented on mobile/src/styles/components/CustomButton.js
> +import React from 'react';
It has an icon in it. From what I understand you can't have an icon in a normal button component

2020-09-08 13:00 UTC, saf94 commented on mobile/src/styles/components/CustomButton.js
> +import React from 'react';
Could we not extend the existing Button component to have the option of having an icon?

2020-09-09 08:54 UTC, jchiversAND approved these changes

2020-09-09 09:52 UTC, ndeasy commented on mobile/src/styles/components/ViewContainer.js
> +  margin-bottom: ${(props) => (props.marginBottom !== undefined ? props.marginBottom : '')};
is empty string a valid value ? ` : '' `

2020-09-09 09:54 UTC, ndeasy commented on mobile/src/screens/SportsAccountScreen/SportsAccountScreen.jsx
> +            <Text margin={'0px 0px 40px 0px'}>Let us know about other services you use so we can decide which one to add next</Text>
Could just use marginBottom

2020-09-09 09:55 UTC, ndeasy approved these changes

2020-09-09 09:58 UTC, merged