Feature/message us on setting page
Revenite/amputee-rehab-app-monorepo pull request #180
Opened 2020-12-03 12:28 UTC by Eliasadam

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2020-12-03 12:34 UTC, Eliasadam commented
Linking not supported on IOS simulator but we should be able to navigate in real ios device

2020-12-03 12:44 UTC, manasamanjunath28 approved these changes
Looks good 👍 Good implementation.
Works fine in IOS real device as well in Android phone

2020-12-07 11:08 UTC, Ehuf requested changes

2020-12-07 11:08 UTC, Ehuf commented on mobile/src/screens/SettingsScreen/SettingsScreen.jsx
> +    Linking.openURL('mailto:reveniters@gmail.com');
This email address shouldn't be hardcoded into the codebase. It should be stored as an environment variable so that if it's ever updated it's updated there.

2020-12-09 10:30 UTC, Ehuf approved these changes

2020-12-09 10:45 UTC, merged